CREATE TABLE IF NOT EXISTS tags
(
    id         INT AUTO_INCREMENT PRIMARY KEY,
    tag_name   VARCHAR(100) NOT NULL,
    created_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);